DATASET:
  DATA1: "mnist" # "mnist (28x28x1)", "cifar10 (32x32x3)", "cifar100 (32x32x3)", "imagenet"
  NUM_CLASSES1: 10
  DATA2: "mnist"
  NUM_CLASSES2: 10
  PATH: "data/"
  TRAIN_BATCH_SIZE: 128 #64
  TEST_BATCH_SIZE: 64
MODEL:
  BASE_MODEL: "mlp"
  CHECKPOINT: "checkpoint_99.pth.tar"
  CONVERGENCE_THRESHOLD: 1e-4
SOLVER:
  EPOCH: 100
  LR: 1e-3
  OPTIMIZER: "SGD"
  MOMENTUM: 0
  DROPOUT: 0
  BN_MOMENTUM: 1e-2
  WEIGHT_DECAY: 1e-5
ETC:
  WORKERS: 16
  VERBOSE: True
  SEED: 0