DATASET:
  DATA1: "cifar10"
  NUM_CLASSES1: 10
  DATA2: "cifar100"
  NUM_CLASSES2: 100
  PATH: "data/"
  TRAIN_BATCH_SIZE: 128 #64
  TEST_BATCH_SIZE: 64
MODEL:
  BASE_MODEL: "cnn" # "mlp", "cnn", "resnet18"
  NUM_LAYERS: 3
  HIDDEN_SIZE: 128
  CHECKPOINT: "checkpoint_99.pth.tar"
  CONVERGENCE_THRESHOLD: 1e-4
SOLVER:
  EPOCH: 100
  LR: 1e-3
  OPTIMIZER: "SGD"
  MOMENTUM: 0
  DROPOUT: 0
  BN_MOMENTUM: 1e-2
  WEIGHT_DECAY: 1e-5
  CHECKPOINT_PERIOD: 10
ETC:
  WORKERS: 16
  VERBOSE: True
  SEED: 0